### ISSUE TITLE
Create setup.py file

### ISSUE THREAD

**Issue by LuisanaMT2005** [LuisanaMT2005/DailyTasks#2]
**Do this in integrate-click branch !!!**.

This file is for working easiest in the development.

**Comment by Krishnag09** [comment]
Hi @LuisanaMT2005 - can i help you with this? please assign and give me the access.

**Comment by Krishnag09** [comment]
> > Hi @LuisanaMT2005 - can i help you with this? please assign and give me the access.
> 
> Please only change setup.py file in the integrate-click branch and then make a PR.

thanks, i would also need access to push my code.

**Comment by LuisanaMT2005** [comment]
> > > Hi @LuisanaMT2005 - can i help you with this? please assign and give me the access.
> > 
> > Please only change setup.py file in the integrate-click branch and then make a PR.
> 
> thanks, i would also need access to push my code.

It's done, sorry for making you wait.

**Comment by Krishnag09** [comment]
thanks a lot. if you would like i could also add tests, i saw some suggestions in main.py/

**Comment by LuisanaMT2005** [comment]
> thanks a lot. if you would like i could also add tests, i saw some suggestions in main.py.  if yes please create a feature for it. 

I really like the idea!!!.

If you want to contribute more please read the [Contributing file](https://github.com/LuisanaMT2005/DailyTasks/blob/main/CONTRIBUTING.md)

And I will review your PR tomorrow, it is very late in my country.
